### ISSUE TITLE
 android.view.WindowManager$BadTokenException

### ISSUE THREAD

**Issue by Pratikk460** [ViHtarb/Tooltip#44]
Hello,
I am using these Tooltips to create a Intro Session for my app.
Its fine in almost every phone but I started getting this error in HTC Desire 10 Pro.
Below stated is the error please look into it : 
FATAL EXCEPTION: main
                                                                    Process: com.jdotnet.orderapp, PID: 4300
                                                                    android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
                                                                        at android.view.ViewRootImpl.setView(ViewRootImpl.java:703)
                                                                        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:319)
                                                                        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
                                                                        at android.widget.PopupWindow.invokePopup(PopupWindow.java:1272)
                                                                        at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1119)
                                                                        at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1078)
                                                                        at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1057)
                                                                        at com.tooltip.Tooltip$2.run(Tooltip.java:211)

-- Error Appears when the user presses back and goes back to the previous activity while the tooltip is present, it will crash the app giving this error or Sometimes if the user stays too long on the same activity with the tooltip on it would crash and give the same error. 
This error only appears on HTC Desire 10 Pro.

**Comment by ViHtarb** [comment]
Hi. What version of Tooltip you use?

**Comment by Pratikk460** [comment]
I used com.github.vihtarb:tooltip:0.1.9 but now I am using snapshot version
and its working great.
Thankyou.
